d = [
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/1.wav",
        "result": {
            "segments": [
                {
                    "start": 0.232,
                    "end": 9.942,
                    "text": " In 1950, physicist Enrico Fermi questioned why humanity had found no evidence of extraterrestrial civilizations despite the vast number of potentially habitable planets.",
                    "words": [
                        {"word": "In", "start": 0.232, "end": 0.292, "score": 1.0},
                        {"word": "1950,", "start": 0.352, "end": 1.155, "score": 0.706},
                        {
                            "word": "physicist",
                            "start": 1.375,
                            "end": 1.877,
                            "score": 0.887,
                        },
                        {"word": "Enrico", "start": 1.937, "end": 2.358, "score": 0.68},
                        {"word": "Fermi", "start": 2.398, "end": 2.719, "score": 0.837},
                        {
                            "word": "questioned",
                            "start": 2.76,
                            "end": 3.161,
                            "score": 0.788,
                        },
                        {"word": "why", "start": 3.201, "end": 3.361, "score": 0.878},
                        {
                            "word": "humanity",
                            "start": 3.422,
                            "end": 3.923,
                            "score": 0.88,
                        },
                        {"word": "had", "start": 3.983, "end": 4.084, "score": 0.851},
                        {"word": "found", "start": 4.124, "end": 4.345, "score": 0.866},
                        {"word": "no", "start": 4.425, "end": 4.585, "score": 0.846},
                        {
                            "word": "evidence",
                            "start": 4.726,
                            "end": 5.067,
                            "score": 0.916,
                        },
                        {"word": "of", "start": 5.107, "end": 5.167, "score": 0.75},
                        {
                            "word": "extraterrestrial",
                            "start": 5.308,
                            "end": 6.11,
                            "score": 0.853,
                        },
                        {
                            "word": "civilizations",
                            "start": 6.17,
                            "end": 6.953,
                            "score": 0.87,
                        },
                        {
                            "word": "despite",
                            "start": 7.033,
                            "end": 7.434,
                            "score": 0.824,
                        },
                        {"word": "the", "start": 7.454, "end": 7.555, "score": 0.993},
                        {"word": "vast", "start": 7.615, "end": 7.996, "score": 0.734},
                        {
                            "word": "number",
                            "start": 8.076,
                            "end": 8.317,
                            "score": 0.891,
                        },
                        {"word": "of", "start": 8.337, "end": 8.397, "score": 0.75},
                        {
                            "word": "potentially",
                            "start": 8.457,
                            "end": 8.959,
                            "score": 0.939,
                        },
                        {
                            "word": "habitable",
                            "start": 9.019,
                            "end": 9.461,
                            "score": 0.878,
                        },
                        {
                            "word": "planets.",
                            "start": 9.521,
                            "end": 9.942,
                            "score": 0.823,
                        },
                    ],
                    "avg_logprob": -0.010309157396356265,
                }
            ],
            "word_segments": [
                {"word": "In", "start": 0.232, "end": 0.292, "score": 1.0},
                {"word": "1950,", "start": 0.352, "end": 1.155, "score": 0.706},
                {"word": "physicist", "start": 1.375, "end": 1.877, "score": 0.887},
                {"word": "Enrico", "start": 1.937, "end": 2.358, "score": 0.68},
                {"word": "Fermi", "start": 2.398, "end": 2.719, "score": 0.837},
                {"word": "questioned", "start": 2.76, "end": 3.161, "score": 0.788},
                {"word": "why", "start": 3.201, "end": 3.361, "score": 0.878},
                {"word": "humanity", "start": 3.422, "end": 3.923, "score": 0.88},
                {"word": "had", "start": 3.983, "end": 4.084, "score": 0.851},
                {"word": "found", "start": 4.124, "end": 4.345, "score": 0.866},
                {"word": "no", "start": 4.425, "end": 4.585, "score": 0.846},
                {"word": "evidence", "start": 4.726, "end": 5.067, "score": 0.916},
                {"word": "of", "start": 5.107, "end": 5.167, "score": 0.75},
                {
                    "word": "extraterrestrial",
                    "start": 5.308,
                    "end": 6.11,
                    "score": 0.853,
                },
                {"word": "civilizations", "start": 6.17, "end": 6.953, "score": 0.87},
                {"word": "despite", "start": 7.033, "end": 7.434, "score": 0.824},
                {"word": "the", "start": 7.454, "end": 7.555, "score": 0.993},
                {"word": "vast", "start": 7.615, "end": 7.996, "score": 0.734},
                {"word": "number", "start": 8.076, "end": 8.317, "score": 0.891},
                {"word": "of", "start": 8.337, "end": 8.397, "score": 0.75},
                {"word": "potentially", "start": 8.457, "end": 8.959, "score": 0.939},
                {"word": "habitable", "start": 9.019, "end": 9.461, "score": 0.878},
                {"word": "planets.", "start": 9.521, "end": 9.942, "score": 0.823},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/2.wav",
        "result": {
            "segments": [
                {
                    "start": 0.212,
                    "end": 8.674,
                    "text": " His simple question, where is everybody, highlighted a contradiction, the high probability of life existing elsewhere and the absence of any detectable signs?",
                    "words": [
                        {"word": "His", "start": 0.212, "end": 0.353, "score": 0.568},
                        {
                            "word": "simple",
                            "start": 0.393,
                            "end": 0.674,
                            "score": 0.881,
                        },
                        {
                            "word": "question,",
                            "start": 0.714,
                            "end": 1.177,
                            "score": 0.86,
                        },
                        {"word": "where", "start": 1.699, "end": 1.9, "score": 0.703},
                        {"word": "is", "start": 1.96, "end": 2.041, "score": 0.969},
                        {
                            "word": "everybody,",
                            "start": 2.141,
                            "end": 2.604,
                            "score": 0.923,
                        },
                        {
                            "word": "highlighted",
                            "start": 2.805,
                            "end": 3.247,
                            "score": 0.826,
                        },
                        {"word": "a", "start": 3.287, "end": 3.307, "score": 0.977},
                        {
                            "word": "contradiction,",
                            "start": 3.367,
                            "end": 4.031,
                            "score": 0.841,
                        },
                        {"word": "the", "start": 4.091, "end": 4.191, "score": 0.893},
                        {"word": "high", "start": 4.232, "end": 4.433, "score": 0.76},
                        {
                            "word": "probability",
                            "start": 4.473,
                            "end": 5.096,
                            "score": 0.871,
                        },
                        {"word": "of", "start": 5.116, "end": 5.196, "score": 0.67},
                        {"word": "life", "start": 5.257, "end": 5.458, "score": 0.756},
                        {
                            "word": "existing",
                            "start": 5.538,
                            "end": 5.98,
                            "score": 0.802,
                        },
                        {
                            "word": "elsewhere",
                            "start": 6.121,
                            "end": 6.543,
                            "score": 0.704,
                        },
                        {"word": "and", "start": 6.664, "end": 6.744, "score": 0.833},
                        {"word": "the", "start": 6.764, "end": 6.845, "score": 0.836},
                        {
                            "word": "absence",
                            "start": 6.945,
                            "end": 7.267,
                            "score": 0.835,
                        },
                        {"word": "of", "start": 7.307, "end": 7.367, "score": 0.751},
                        {"word": "any", "start": 7.447, "end": 7.588, "score": 0.827},
                        {
                            "word": "detectable",
                            "start": 7.628,
                            "end": 8.171,
                            "score": 0.859,
                        },
                        {
                            "word": "signs?",
                            "start": 8.231,
                            "end": 8.674,
                            "score": 0.855,
                        },
                    ],
                    "avg_logprob": -0.09929632421197562,
                }
            ],
            "word_segments": [
                {"word": "His", "start": 0.212, "end": 0.353, "score": 0.568},
                {"word": "simple", "start": 0.393, "end": 0.674, "score": 0.881},
                {"word": "question,", "start": 0.714, "end": 1.177, "score": 0.86},
                {"word": "where", "start": 1.699, "end": 1.9, "score": 0.703},
                {"word": "is", "start": 1.96, "end": 2.041, "score": 0.969},
                {"word": "everybody,", "start": 2.141, "end": 2.604, "score": 0.923},
                {"word": "highlighted", "start": 2.805, "end": 3.247, "score": 0.826},
                {"word": "a", "start": 3.287, "end": 3.307, "score": 0.977},
                {
                    "word": "contradiction,",
                    "start": 3.367,
                    "end": 4.031,
                    "score": 0.841,
                },
                {"word": "the", "start": 4.091, "end": 4.191, "score": 0.893},
                {"word": "high", "start": 4.232, "end": 4.433, "score": 0.76},
                {"word": "probability", "start": 4.473, "end": 5.096, "score": 0.871},
                {"word": "of", "start": 5.116, "end": 5.196, "score": 0.67},
                {"word": "life", "start": 5.257, "end": 5.458, "score": 0.756},
                {"word": "existing", "start": 5.538, "end": 5.98, "score": 0.802},
                {"word": "elsewhere", "start": 6.121, "end": 6.543, "score": 0.704},
                {"word": "and", "start": 6.664, "end": 6.744, "score": 0.833},
                {"word": "the", "start": 6.764, "end": 6.845, "score": 0.836},
                {"word": "absence", "start": 6.945, "end": 7.267, "score": 0.835},
                {"word": "of", "start": 7.307, "end": 7.367, "score": 0.751},
                {"word": "any", "start": 7.447, "end": 7.588, "score": 0.827},
                {"word": "detectable", "start": 7.628, "end": 8.171, "score": 0.859},
                {"word": "signs?", "start": 8.231, "end": 8.674, "score": 0.855},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/3.wav",
        "result": {
            "segments": [
                {
                    "start": 0.232,
                    "end": 6.879,
                    "text": " Fermi's discussion at Los Alamos focused not on life's existence, but on the feasibility of interstellar travel and colonization.",
                    "words": [
                        {
                            "word": "Fermi's",
                            "start": 0.232,
                            "end": 0.573,
                            "score": 0.602,
                        },
                        {
                            "word": "discussion",
                            "start": 0.613,
                            "end": 1.075,
                            "score": 0.909,
                        },
                        {"word": "at", "start": 1.115, "end": 1.176, "score": 0.988},
                        {"word": "Los", "start": 1.216, "end": 1.437, "score": 0.988},
                        {
                            "word": "Alamos",
                            "start": 1.517,
                            "end": 1.939,
                            "score": 0.921,
                        },
                        {
                            "word": "focused",
                            "start": 1.999,
                            "end": 2.34,
                            "score": 0.764,
                        },
                        {"word": "not", "start": 2.401, "end": 2.561, "score": 0.752},
                        {"word": "on", "start": 2.621, "end": 2.682, "score": 0.806},
                        {
                            "word": "life's",
                            "start": 2.722,
                            "end": 2.983,
                            "score": 0.839,
                        },
                        {
                            "word": "existence,",
                            "start": 3.023,
                            "end": 3.505,
                            "score": 0.919,
                        },
                        {"word": "but", "start": 3.846, "end": 3.947, "score": 0.981},
                        {"word": "on", "start": 4.007, "end": 4.067, "score": 0.996},
                        {"word": "the", "start": 4.107, "end": 4.168, "score": 1.0},
                        {
                            "word": "feasibility",
                            "start": 4.188,
                            "end": 4.81,
                            "score": 0.924,
                        },
                        {"word": "of", "start": 4.83, "end": 4.911, "score": 0.666},
                        {
                            "word": "interstellar",
                            "start": 4.991,
                            "end": 5.533,
                            "score": 0.908,
                        },
                        {
                            "word": "travel",
                            "start": 5.573,
                            "end": 5.935,
                            "score": 0.939,
                        },
                        {"word": "and", "start": 6.015, "end": 6.095, "score": 0.916},
                        {
                            "word": "colonization.",
                            "start": 6.156,
                            "end": 6.879,
                            "score": 0.904,
                        },
                    ],
                    "avg_logprob": -0.027532451786100864,
                }
            ],
            "word_segments": [
                {"word": "Fermi's", "start": 0.232, "end": 0.573, "score": 0.602},
                {"word": "discussion", "start": 0.613, "end": 1.075, "score": 0.909},
                {"word": "at", "start": 1.115, "end": 1.176, "score": 0.988},
                {"word": "Los", "start": 1.216, "end": 1.437, "score": 0.988},
                {"word": "Alamos", "start": 1.517, "end": 1.939, "score": 0.921},
                {"word": "focused", "start": 1.999, "end": 2.34, "score": 0.764},
                {"word": "not", "start": 2.401, "end": 2.561, "score": 0.752},
                {"word": "on", "start": 2.621, "end": 2.682, "score": 0.806},
                {"word": "life's", "start": 2.722, "end": 2.983, "score": 0.839},
                {"word": "existence,", "start": 3.023, "end": 3.505, "score": 0.919},
                {"word": "but", "start": 3.846, "end": 3.947, "score": 0.981},
                {"word": "on", "start": 4.007, "end": 4.067, "score": 0.996},
                {"word": "the", "start": 4.107, "end": 4.168, "score": 1.0},
                {"word": "feasibility", "start": 4.188, "end": 4.81, "score": 0.924},
                {"word": "of", "start": 4.83, "end": 4.911, "score": 0.666},
                {"word": "interstellar", "start": 4.991, "end": 5.533, "score": 0.908},
                {"word": "travel", "start": 5.573, "end": 5.935, "score": 0.939},
                {"word": "and", "start": 6.015, "end": 6.095, "score": 0.916},
                {"word": "colonization.", "start": 6.156, "end": 6.879, "score": 0.904},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/4.wav",
        "result": {
            "segments": [
                {
                    "start": 0.229,
                    "end": 3.456,
                    "text": " Later, scientists like Carl Sagan and Michael Hart expanded on this.",
                    "words": [
                        {"word": "Later,", "start": 0.229, "end": 0.55, "score": 0.871},
                        {
                            "word": "scientists",
                            "start": 0.59,
                            "end": 1.051,
                            "score": 0.875,
                        },
                        {"word": "like", "start": 1.091, "end": 1.251, "score": 0.851},
                        {"word": "Carl", "start": 1.291, "end": 1.552, "score": 0.761},
                        {"word": "Sagan", "start": 1.592, "end": 1.913, "score": 0.84},
                        {"word": "and", "start": 1.953, "end": 2.033, "score": 0.844},
                        {
                            "word": "Michael",
                            "start": 2.093,
                            "end": 2.353,
                            "score": 0.68,
                        },
                        {"word": "Hart", "start": 2.393, "end": 2.594, "score": 0.686},
                        {
                            "word": "expanded",
                            "start": 2.634,
                            "end": 3.075,
                            "score": 0.915,
                        },
                        {"word": "on", "start": 3.135, "end": 3.215, "score": 0.576},
                        {"word": "this.", "start": 3.255, "end": 3.456, "score": 0.929},
                    ],
                    "avg_logprob": -0.0652036855618159,
                }
            ],
            "word_segments": [
                {"word": "Later,", "start": 0.229, "end": 0.55, "score": 0.871},
                {"word": "scientists", "start": 0.59, "end": 1.051, "score": 0.875},
                {"word": "like", "start": 1.091, "end": 1.251, "score": 0.851},
                {"word": "Carl", "start": 1.291, "end": 1.552, "score": 0.761},
                {"word": "Sagan", "start": 1.592, "end": 1.913, "score": 0.84},
                {"word": "and", "start": 1.953, "end": 2.033, "score": 0.844},
                {"word": "Michael", "start": 2.093, "end": 2.353, "score": 0.68},
                {"word": "Hart", "start": 2.393, "end": 2.594, "score": 0.686},
                {"word": "expanded", "start": 2.634, "end": 3.075, "score": 0.915},
                {"word": "on", "start": 3.135, "end": 3.215, "score": 0.576},
                {"word": "this.", "start": 3.255, "end": 3.456, "score": 0.929},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/5.wav",
        "result": {
            "segments": [
                {
                    "start": 0.453,
                    "end": 6.79,
                    "text": " Introducing the concept of a great filter, a barrier, preventing life from evolving or surviving long enough to be detected.",
                    "words": [
                        {
                            "word": "Introducing",
                            "start": 0.453,
                            "end": 0.936,
                            "score": 0.908,
                        },
                        {"word": "the", "start": 0.976, "end": 1.057, "score": 0.833},
                        {
                            "word": "concept",
                            "start": 1.097,
                            "end": 1.519,
                            "score": 0.851,
                        },
                        {"word": "of", "start": 1.56, "end": 1.62, "score": 0.874},
                        {"word": "a", "start": 1.68, "end": 1.701, "score": 0.999},
                        {"word": "great", "start": 1.741, "end": 1.982, "score": 0.903},
                        {
                            "word": "filter,",
                            "start": 2.042,
                            "end": 2.445,
                            "score": 0.836,
                        },
                        {"word": "a", "start": 2.666, "end": 2.686, "score": 1.0},
                        {
                            "word": "barrier,",
                            "start": 2.726,
                            "end": 3.169,
                            "score": 0.881,
                        },
                        {
                            "word": "preventing",
                            "start": 3.35,
                            "end": 3.813,
                            "score": 0.848,
                        },
                        {"word": "life", "start": 3.873, "end": 4.094, "score": 0.835},
                        {"word": "from", "start": 4.114, "end": 4.235, "score": 0.993},
                        {
                            "word": "evolving",
                            "start": 4.315,
                            "end": 4.798,
                            "score": 0.741,
                        },
                        {"word": "or", "start": 4.919, "end": 4.999, "score": 0.665},
                        {
                            "word": "surviving",
                            "start": 5.06,
                            "end": 5.563,
                            "score": 0.815,
                        },
                        {"word": "long", "start": 5.603, "end": 5.804, "score": 0.813},
                        {
                            "word": "enough",
                            "start": 5.844,
                            "end": 6.045,
                            "score": 0.904,
                        },
                        {"word": "to", "start": 6.085, "end": 6.146, "score": 0.999},
                        {"word": "be", "start": 6.186, "end": 6.267, "score": 0.994},
                        {
                            "word": "detected.",
                            "start": 6.307,
                            "end": 6.79,
                            "score": 0.929,
                        },
                    ],
                    "avg_logprob": -0.035046744346618655,
                }
            ],
            "word_segments": [
                {"word": "Introducing", "start": 0.453, "end": 0.936, "score": 0.908},
                {"word": "the", "start": 0.976, "end": 1.057, "score": 0.833},
                {"word": "concept", "start": 1.097, "end": 1.519, "score": 0.851},
                {"word": "of", "start": 1.56, "end": 1.62, "score": 0.874},
                {"word": "a", "start": 1.68, "end": 1.701, "score": 0.999},
                {"word": "great", "start": 1.741, "end": 1.982, "score": 0.903},
                {"word": "filter,", "start": 2.042, "end": 2.445, "score": 0.836},
                {"word": "a", "start": 2.666, "end": 2.686, "score": 1.0},
                {"word": "barrier,", "start": 2.726, "end": 3.169, "score": 0.881},
                {"word": "preventing", "start": 3.35, "end": 3.813, "score": 0.848},
                {"word": "life", "start": 3.873, "end": 4.094, "score": 0.835},
                {"word": "from", "start": 4.114, "end": 4.235, "score": 0.993},
                {"word": "evolving", "start": 4.315, "end": 4.798, "score": 0.741},
                {"word": "or", "start": 4.919, "end": 4.999, "score": 0.665},
                {"word": "surviving", "start": 5.06, "end": 5.563, "score": 0.815},
                {"word": "long", "start": 5.603, "end": 5.804, "score": 0.813},
                {"word": "enough", "start": 5.844, "end": 6.045, "score": 0.904},
                {"word": "to", "start": 6.085, "end": 6.146, "score": 0.999},
                {"word": "be", "start": 6.186, "end": 6.267, "score": 0.994},
                {"word": "detected.", "start": 6.307, "end": 6.79, "score": 0.929},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/6.wav",
        "result": {
            "segments": [
                {
                    "start": 0.353,
                    "end": 5.753,
                    "text": " Proposed solutions range from the rare Earth hypothesis, suggesting Earth's conditions for life are unique.",
                    "words": [
                        {
                            "word": "Proposed",
                            "start": 0.353,
                            "end": 0.776,
                            "score": 0.891,
                        },
                        {
                            "word": "solutions",
                            "start": 0.797,
                            "end": 1.32,
                            "score": 0.838,
                        },
                        {"word": "range", "start": 1.421, "end": 1.683, "score": 0.889},
                        {"word": "from", "start": 1.723, "end": 1.844, "score": 0.894},
                        {"word": "the", "start": 1.884, "end": 1.945, "score": 0.989},
                        {"word": "rare", "start": 2.005, "end": 2.227, "score": 0.8},
                        {"word": "Earth", "start": 2.267, "end": 2.449, "score": 0.73},
                        {
                            "word": "hypothesis,",
                            "start": 2.469,
                            "end": 3.194,
                            "score": 0.816,
                        },
                        {
                            "word": "suggesting",
                            "start": 3.637,
                            "end": 4.141,
                            "score": 0.844,
                        },
                        {
                            "word": "Earth's",
                            "start": 4.181,
                            "end": 4.383,
                            "score": 0.819,
                        },
                        {
                            "word": "conditions",
                            "start": 4.423,
                            "end": 4.826,
                            "score": 0.911,
                        },
                        {"word": "for", "start": 4.866, "end": 4.987, "score": 0.853},
                        {"word": "life", "start": 5.027, "end": 5.229, "score": 0.828},
                        {"word": "are", "start": 5.269, "end": 5.35, "score": 0.331},
                        {
                            "word": "unique.",
                            "start": 5.45,
                            "end": 5.753,
                            "score": 0.877,
                        },
                    ],
                    "avg_logprob": -0.14629781916737555,
                }
            ],
            "word_segments": [
                {"word": "Proposed", "start": 0.353, "end": 0.776, "score": 0.891},
                {"word": "solutions", "start": 0.797, "end": 1.32, "score": 0.838},
                {"word": "range", "start": 1.421, "end": 1.683, "score": 0.889},
                {"word": "from", "start": 1.723, "end": 1.844, "score": 0.894},
                {"word": "the", "start": 1.884, "end": 1.945, "score": 0.989},
                {"word": "rare", "start": 2.005, "end": 2.227, "score": 0.8},
                {"word": "Earth", "start": 2.267, "end": 2.449, "score": 0.73},
                {"word": "hypothesis,", "start": 2.469, "end": 3.194, "score": 0.816},
                {"word": "suggesting", "start": 3.637, "end": 4.141, "score": 0.844},
                {"word": "Earth's", "start": 4.181, "end": 4.383, "score": 0.819},
                {"word": "conditions", "start": 4.423, "end": 4.826, "score": 0.911},
                {"word": "for", "start": 4.866, "end": 4.987, "score": 0.853},
                {"word": "life", "start": 5.027, "end": 5.229, "score": 0.828},
                {"word": "are", "start": 5.269, "end": 5.35, "score": 0.331},
                {"word": "unique.", "start": 5.45, "end": 5.753, "score": 0.877},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/7.wav",
        "result": {
            "segments": [
                {
                    "start": 0.091,
                    "end": 4.66,
                    "text": " to the dark forest hypothesis, where civilizations remain silent to avoid detection.",
                    "words": [
                        {"word": "to", "start": 0.091, "end": 0.232, "score": 0.949},
                        {"word": "the", "start": 0.252, "end": 0.313, "score": 0.977},
                        {"word": "dark", "start": 0.353, "end": 0.574, "score": 0.872},
                        {
                            "word": "forest",
                            "start": 0.635,
                            "end": 0.957,
                            "score": 0.779,
                        },
                        {
                            "word": "hypothesis,",
                            "start": 0.977,
                            "end": 1.702,
                            "score": 0.852,
                        },
                        {"word": "where", "start": 1.883, "end": 2.024, "score": 0.919},
                        {
                            "word": "civilizations",
                            "start": 2.084,
                            "end": 2.829,
                            "score": 0.885,
                        },
                        {
                            "word": "remain",
                            "start": 2.889,
                            "end": 3.191,
                            "score": 0.716,
                        },
                        {"word": "silent", "start": 3.251, "end": 3.634, "score": 0.87},
                        {"word": "to", "start": 3.694, "end": 3.795, "score": 0.832},
                        {"word": "avoid", "start": 3.835, "end": 4.117, "score": 0.793},
                        {
                            "word": "detection.",
                            "start": 4.157,
                            "end": 4.66,
                            "score": 0.911,
                        },
                    ],
                    "avg_logprob": -0.11731165250142415,
                }
            ],
            "word_segments": [
                {"word": "to", "start": 0.091, "end": 0.232, "score": 0.949},
                {"word": "the", "start": 0.252, "end": 0.313, "score": 0.977},
                {"word": "dark", "start": 0.353, "end": 0.574, "score": 0.872},
                {"word": "forest", "start": 0.635, "end": 0.957, "score": 0.779},
                {"word": "hypothesis,", "start": 0.977, "end": 1.702, "score": 0.852},
                {"word": "where", "start": 1.883, "end": 2.024, "score": 0.919},
                {"word": "civilizations", "start": 2.084, "end": 2.829, "score": 0.885},
                {"word": "remain", "start": 2.889, "end": 3.191, "score": 0.716},
                {"word": "silent", "start": 3.251, "end": 3.634, "score": 0.87},
                {"word": "to", "start": 3.694, "end": 3.795, "score": 0.832},
                {"word": "avoid", "start": 3.835, "end": 4.117, "score": 0.793},
                {"word": "detection.", "start": 4.157, "end": 4.66, "score": 0.911},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/8.wav",
        "result": {
            "segments": [
                {
                    "start": 0.272,
                    "end": 4.356,
                    "text": " Others propose civilization self-destruct through war or environmental collapse.",
                    "words": [
                        {
                            "word": "Others",
                            "start": 0.272,
                            "end": 0.494,
                            "score": 0.861,
                        },
                        {
                            "word": "propose",
                            "start": 0.554,
                            "end": 0.916,
                            "score": 0.95,
                        },
                        {
                            "word": "civilization",
                            "start": 0.956,
                            "end": 1.721,
                            "score": 0.858,
                        },
                        {
                            "word": "self-destruct",
                            "start": 1.781,
                            "end": 2.425,
                            "score": 0.874,
                        },
                        {
                            "word": "through",
                            "start": 2.445,
                            "end": 2.666,
                            "score": 0.777,
                        },
                        {"word": "war", "start": 2.707, "end": 2.968, "score": 0.864},
                        {"word": "or", "start": 3.089, "end": 3.19, "score": 0.637},
                        {
                            "word": "environmental",
                            "start": 3.25,
                            "end": 3.874,
                            "score": 0.803,
                        },
                        {
                            "word": "collapse.",
                            "start": 3.914,
                            "end": 4.356,
                            "score": 0.896,
                        },
                    ],
                    "avg_logprob": -0.03384705340223653,
                }
            ],
            "word_segments": [
                {"word": "Others", "start": 0.272, "end": 0.494, "score": 0.861},
                {"word": "propose", "start": 0.554, "end": 0.916, "score": 0.95},
                {"word": "civilization", "start": 0.956, "end": 1.721, "score": 0.858},
                {"word": "self-destruct", "start": 1.781, "end": 2.425, "score": 0.874},
                {"word": "through", "start": 2.445, "end": 2.666, "score": 0.777},
                {"word": "war", "start": 2.707, "end": 2.968, "score": 0.864},
                {"word": "or", "start": 3.089, "end": 3.19, "score": 0.637},
                {"word": "environmental", "start": 3.25, "end": 3.874, "score": 0.803},
                {"word": "collapse.", "start": 3.914, "end": 4.356, "score": 0.896},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/9.wav",
        "result": {
            "segments": [
                {
                    "start": 0.226,
                    "end": 4.022,
                    "text": " or that they exist but deliberately avoid contact as in the zoo hypothesis.",
                    "words": [
                        {"word": "or", "start": 0.226, "end": 0.286, "score": 0.855},
                        {"word": "that", "start": 0.327, "end": 0.447, "score": 0.759},
                        {"word": "they", "start": 0.467, "end": 0.608, "score": 0.688},
                        {"word": "exist", "start": 0.668, "end": 1.03, "score": 0.907},
                        {"word": "but", "start": 1.09, "end": 1.21, "score": 0.835},
                        {
                            "word": "deliberately",
                            "start": 1.25,
                            "end": 1.793,
                            "score": 0.849,
                        },
                        {"word": "avoid", "start": 1.833, "end": 2.114, "score": 0.829},
                        {
                            "word": "contact",
                            "start": 2.154,
                            "end": 2.656,
                            "score": 0.932,
                        },
                        {"word": "as", "start": 2.777, "end": 2.877, "score": 0.724},
                        {"word": "in", "start": 2.917, "end": 2.978, "score": 0.754},
                        {"word": "the", "start": 3.018, "end": 3.078, "score": 0.992},
                        {"word": "zoo", "start": 3.118, "end": 3.319, "score": 0.891},
                        {
                            "word": "hypothesis.",
                            "start": 3.339,
                            "end": 4.022,
                            "score": 0.907,
                        },
                    ],
                    "avg_logprob": -0.09704255263010661,
                }
            ],
            "word_segments": [
                {"word": "or", "start": 0.226, "end": 0.286, "score": 0.855},
                {"word": "that", "start": 0.327, "end": 0.447, "score": 0.759},
                {"word": "they", "start": 0.467, "end": 0.608, "score": 0.688},
                {"word": "exist", "start": 0.668, "end": 1.03, "score": 0.907},
                {"word": "but", "start": 1.09, "end": 1.21, "score": 0.835},
                {"word": "deliberately", "start": 1.25, "end": 1.793, "score": 0.849},
                {"word": "avoid", "start": 1.833, "end": 2.114, "score": 0.829},
                {"word": "contact", "start": 2.154, "end": 2.656, "score": 0.932},
                {"word": "as", "start": 2.777, "end": 2.877, "score": 0.724},
                {"word": "in", "start": 2.917, "end": 2.978, "score": 0.754},
                {"word": "the", "start": 3.018, "end": 3.078, "score": 0.992},
                {"word": "zoo", "start": 3.118, "end": 3.319, "score": 0.891},
                {"word": "hypothesis.", "start": 3.339, "end": 4.022, "score": 0.907},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/10.wav",
        "result": {
            "segments": [
                {
                    "start": 0.292,
                    "end": 10.057,
                    "text": " SETI programs like Project OSMA in 1960 and the Allen Telescope Array have searched for radio signals from extraterrestrial civilizations so far without conclusive evidence.",
                    "words": [
                        {"word": "SETI", "start": 0.292, "end": 0.553, "score": 0.848},
                        {
                            "word": "programs",
                            "start": 0.594,
                            "end": 1.096,
                            "score": 0.767,
                        },
                        {"word": "like", "start": 1.176, "end": 1.337, "score": 0.764},
                        {
                            "word": "Project",
                            "start": 1.377,
                            "end": 1.759,
                            "score": 0.891,
                        },
                        {"word": "OSMA", "start": 1.859, "end": 2.121, "score": 0.796},
                        {"word": "in", "start": 2.181, "end": 2.241, "score": 0.879},
                        {"word": "1960", "start": 2.342, "end": 3.045, "score": 0.523},
                        {"word": "and", "start": 3.145, "end": 3.226, "score": 0.861},
                        {"word": "the", "start": 3.246, "end": 3.306, "score": 0.999},
                        {"word": "Allen", "start": 3.406, "end": 3.627, "score": 0.676},
                        {
                            "word": "Telescope",
                            "start": 3.647,
                            "end": 4.13,
                            "score": 0.776,
                        },
                        {"word": "Array", "start": 4.17, "end": 4.431, "score": 0.861},
                        {"word": "have", "start": 4.612, "end": 4.732, "score": 0.955},
                        {
                            "word": "searched",
                            "start": 4.773,
                            "end": 5.054,
                            "score": 0.893,
                        },
                        {"word": "for", "start": 5.094, "end": 5.215, "score": 0.872},
                        {"word": "radio", "start": 5.315, "end": 5.697, "score": 0.933},
                        {
                            "word": "signals",
                            "start": 5.757,
                            "end": 6.119,
                            "score": 0.826,
                        },
                        {"word": "from", "start": 6.159, "end": 6.279, "score": 0.766},
                        {
                            "word": "extraterrestrial",
                            "start": 6.38,
                            "end": 7.143,
                            "score": 0.911,
                        },
                        {
                            "word": "civilizations",
                            "start": 7.184,
                            "end": 8.007,
                            "score": 0.911,
                        },
                        {"word": "so", "start": 8.309, "end": 8.489, "score": 0.859},
                        {"word": "far", "start": 8.53, "end": 8.731, "score": 0.919},
                        {
                            "word": "without",
                            "start": 8.791,
                            "end": 9.072,
                            "score": 0.796,
                        },
                        {
                            "word": "conclusive",
                            "start": 9.112,
                            "end": 9.595,
                            "score": 0.928,
                        },
                        {
                            "word": "evidence.",
                            "start": 9.655,
                            "end": 10.057,
                            "score": 0.939,
                        },
                    ],
                    "avg_logprob": -0.0730761686230407,
                }
            ],
            "word_segments": [
                {"word": "SETI", "start": 0.292, "end": 0.553, "score": 0.848},
                {"word": "programs", "start": 0.594, "end": 1.096, "score": 0.767},
                {"word": "like", "start": 1.176, "end": 1.337, "score": 0.764},
                {"word": "Project", "start": 1.377, "end": 1.759, "score": 0.891},
                {"word": "OSMA", "start": 1.859, "end": 2.121, "score": 0.796},
                {"word": "in", "start": 2.181, "end": 2.241, "score": 0.879},
                {"word": "1960", "start": 2.342, "end": 3.045, "score": 0.523},
                {"word": "and", "start": 3.145, "end": 3.226, "score": 0.861},
                {"word": "the", "start": 3.246, "end": 3.306, "score": 0.999},
                {"word": "Allen", "start": 3.406, "end": 3.627, "score": 0.676},
                {"word": "Telescope", "start": 3.647, "end": 4.13, "score": 0.776},
                {"word": "Array", "start": 4.17, "end": 4.431, "score": 0.861},
                {"word": "have", "start": 4.612, "end": 4.732, "score": 0.955},
                {"word": "searched", "start": 4.773, "end": 5.054, "score": 0.893},
                {"word": "for", "start": 5.094, "end": 5.215, "score": 0.872},
                {"word": "radio", "start": 5.315, "end": 5.697, "score": 0.933},
                {"word": "signals", "start": 5.757, "end": 6.119, "score": 0.826},
                {"word": "from", "start": 6.159, "end": 6.279, "score": 0.766},
                {
                    "word": "extraterrestrial",
                    "start": 6.38,
                    "end": 7.143,
                    "score": 0.911,
                },
                {"word": "civilizations", "start": 7.184, "end": 8.007, "score": 0.911},
                {"word": "so", "start": 8.309, "end": 8.489, "score": 0.859},
                {"word": "far", "start": 8.53, "end": 8.731, "score": 0.919},
                {"word": "without", "start": 8.791, "end": 9.072, "score": 0.796},
                {"word": "conclusive", "start": 9.112, "end": 9.595, "score": 0.928},
                {"word": "evidence.", "start": 9.655, "end": 10.057, "score": 0.939},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/11.wav",
        "result": {
            "segments": [
                {
                    "start": 0.513,
                    "end": 5.316,
                    "text": " Exoplanet missions like Kepler and TESS have identified thousands of planets' inhabitable zones.",
                    "words": [
                        {
                            "word": "Exoplanet",
                            "start": 0.513,
                            "end": 1.016,
                            "score": 0.929,
                        },
                        {
                            "word": "missions",
                            "start": 1.036,
                            "end": 1.357,
                            "score": 0.84,
                        },
                        {"word": "like", "start": 1.417, "end": 1.558, "score": 0.942},
                        {"word": "Kepler", "start": 1.618, "end": 1.96, "score": 0.892},
                        {"word": "and", "start": 2.0, "end": 2.081, "score": 0.849},
                        {"word": "TESS", "start": 2.121, "end": 2.422, "score": 0.88},
                        {"word": "have", "start": 2.623, "end": 2.764, "score": 0.846},
                        {
                            "word": "identified",
                            "start": 2.804,
                            "end": 3.306,
                            "score": 0.817,
                        },
                        {
                            "word": "thousands",
                            "start": 3.367,
                            "end": 3.788,
                            "score": 0.804,
                        },
                        {"word": "of", "start": 3.809, "end": 3.869, "score": 0.751},
                        {
                            "word": "planets'",
                            "start": 3.929,
                            "end": 4.271,
                            "score": 0.788,
                        },
                        {
                            "word": "inhabitable",
                            "start": 4.331,
                            "end": 4.894,
                            "score": 0.804,
                        },
                        {
                            "word": "zones.",
                            "start": 4.954,
                            "end": 5.316,
                            "score": 0.991,
                        },
                    ],
                    "avg_logprob": -0.05876311234065464,
                }
            ],
            "word_segments": [
                {"word": "Exoplanet", "start": 0.513, "end": 1.016, "score": 0.929},
                {"word": "missions", "start": 1.036, "end": 1.357, "score": 0.84},
                {"word": "like", "start": 1.417, "end": 1.558, "score": 0.942},
                {"word": "Kepler", "start": 1.618, "end": 1.96, "score": 0.892},
                {"word": "and", "start": 2.0, "end": 2.081, "score": 0.849},
                {"word": "TESS", "start": 2.121, "end": 2.422, "score": 0.88},
                {"word": "have", "start": 2.623, "end": 2.764, "score": 0.846},
                {"word": "identified", "start": 2.804, "end": 3.306, "score": 0.817},
                {"word": "thousands", "start": 3.367, "end": 3.788, "score": 0.804},
                {"word": "of", "start": 3.809, "end": 3.869, "score": 0.751},
                {"word": "planets'", "start": 3.929, "end": 4.271, "score": 0.788},
                {"word": "inhabitable", "start": 4.331, "end": 4.894, "score": 0.804},
                {"word": "zones.", "start": 4.954, "end": 5.316, "score": 0.991},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/12.wav",
        "result": {
            "segments": [
                {
                    "start": 0.574,
                    "end": 3.975,
                    "text": " Increasing the likelihood of Earth-like worlds but not confirming life.",
                    "words": [
                        {
                            "word": "Increasing",
                            "start": 0.574,
                            "end": 1.017,
                            "score": 0.842,
                        },
                        {"word": "the", "start": 1.057, "end": 1.138, "score": 0.833},
                        {
                            "word": "likelihood",
                            "start": 1.178,
                            "end": 1.661,
                            "score": 0.826,
                        },
                        {"word": "of", "start": 1.681, "end": 1.741, "score": 0.75},
                        {
                            "word": "Earth-like",
                            "start": 1.862,
                            "end": 2.345,
                            "score": 0.841,
                        },
                        {
                            "word": "worlds",
                            "start": 2.405,
                            "end": 2.767,
                            "score": 0.752,
                        },
                        {"word": "but", "start": 2.828, "end": 2.948, "score": 0.847},
                        {"word": "not", "start": 3.009, "end": 3.17, "score": 0.839},
                        {
                            "word": "confirming",
                            "start": 3.23,
                            "end": 3.693,
                            "score": 0.881,
                        },
                        {"word": "life.", "start": 3.733, "end": 3.975, "score": 0.95},
                    ],
                    "avg_logprob": -0.13076286713282267,
                }
            ],
            "word_segments": [
                {"word": "Increasing", "start": 0.574, "end": 1.017, "score": 0.842},
                {"word": "the", "start": 1.057, "end": 1.138, "score": 0.833},
                {"word": "likelihood", "start": 1.178, "end": 1.661, "score": 0.826},
                {"word": "of", "start": 1.681, "end": 1.741, "score": 0.75},
                {"word": "Earth-like", "start": 1.862, "end": 2.345, "score": 0.841},
                {"word": "worlds", "start": 2.405, "end": 2.767, "score": 0.752},
                {"word": "but", "start": 2.828, "end": 2.948, "score": 0.847},
                {"word": "not", "start": 3.009, "end": 3.17, "score": 0.839},
                {"word": "confirming", "start": 3.23, "end": 3.693, "score": 0.881},
                {"word": "life.", "start": 3.733, "end": 3.975, "score": 0.95},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/13.wav",
        "result": {
            "segments": [
                {
                    "start": 0.414,
                    "end": 5.308,
                    "text": " Scientists now search for techno signatures, like artificial structures or industrial pollution.",
                    "words": [
                        {
                            "word": "Scientists",
                            "start": 0.414,
                            "end": 0.957,
                            "score": 0.75,
                        },
                        {"word": "now", "start": 1.018, "end": 1.179, "score": 0.888},
                        {"word": "search", "start": 1.28, "end": 1.521, "score": 0.912},
                        {"word": "for", "start": 1.541, "end": 1.662, "score": 0.723},
                        {
                            "word": "techno",
                            "start": 1.703,
                            "end": 2.045,
                            "score": 0.908,
                        },
                        {
                            "word": "signatures,",
                            "start": 2.085,
                            "end": 2.689,
                            "score": 0.78,
                        },
                        {"word": "like", "start": 2.911, "end": 3.072, "score": 0.746},
                        {
                            "word": "artificial",
                            "start": 3.153,
                            "end": 3.636,
                            "score": 0.828,
                        },
                        {
                            "word": "structures",
                            "start": 3.696,
                            "end": 4.2,
                            "score": 0.813,
                        },
                        {"word": "or", "start": 4.26, "end": 4.341, "score": 0.702},
                        {
                            "word": "industrial",
                            "start": 4.381,
                            "end": 4.865,
                            "score": 0.821,
                        },
                        {
                            "word": "pollution.",
                            "start": 4.905,
                            "end": 5.308,
                            "score": 0.967,
                        },
                    ],
                    "avg_logprob": -0.11244571308294932,
                }
            ],
            "word_segments": [
                {"word": "Scientists", "start": 0.414, "end": 0.957, "score": 0.75},
                {"word": "now", "start": 1.018, "end": 1.179, "score": 0.888},
                {"word": "search", "start": 1.28, "end": 1.521, "score": 0.912},
                {"word": "for", "start": 1.541, "end": 1.662, "score": 0.723},
                {"word": "techno", "start": 1.703, "end": 2.045, "score": 0.908},
                {"word": "signatures,", "start": 2.085, "end": 2.689, "score": 0.78},
                {"word": "like", "start": 2.911, "end": 3.072, "score": 0.746},
                {"word": "artificial", "start": 3.153, "end": 3.636, "score": 0.828},
                {"word": "structures", "start": 3.696, "end": 4.2, "score": 0.813},
                {"word": "or", "start": 4.26, "end": 4.341, "score": 0.702},
                {"word": "industrial", "start": 4.381, "end": 4.865, "score": 0.821},
                {"word": "pollution.", "start": 4.905, "end": 5.308, "score": 0.967},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/14.wav",
        "result": {
            "segments": [
                {
                    "start": 0.272,
                    "end": 3.708,
                    "text": " and biosignatures such as atmospheric chemicals indicating life.",
                    "words": [
                        {"word": "and", "start": 0.272, "end": 0.373, "score": 0.79},
                        {
                            "word": "biosignatures",
                            "start": 0.413,
                            "end": 1.257,
                            "score": 0.858,
                        },
                        {"word": "such", "start": 1.478, "end": 1.638, "score": 0.968},
                        {"word": "as", "start": 1.699, "end": 1.779, "score": 0.73},
                        {
                            "word": "atmospheric",
                            "start": 1.859,
                            "end": 2.342,
                            "score": 0.904,
                        },
                        {
                            "word": "chemicals",
                            "start": 2.382,
                            "end": 2.804,
                            "score": 0.875,
                        },
                        {
                            "word": "indicating",
                            "start": 2.904,
                            "end": 3.386,
                            "score": 0.95,
                        },
                        {"word": "life.", "start": 3.447, "end": 3.708, "score": 0.949},
                    ],
                    "avg_logprob": -0.050928320114811264,
                }
            ],
            "word_segments": [
                {"word": "and", "start": 0.272, "end": 0.373, "score": 0.79},
                {"word": "biosignatures", "start": 0.413, "end": 1.257, "score": 0.858},
                {"word": "such", "start": 1.478, "end": 1.638, "score": 0.968},
                {"word": "as", "start": 1.699, "end": 1.779, "score": 0.73},
                {"word": "atmospheric", "start": 1.859, "end": 2.342, "score": 0.904},
                {"word": "chemicals", "start": 2.382, "end": 2.804, "score": 0.875},
                {"word": "indicating", "start": 2.904, "end": 3.386, "score": 0.95},
                {"word": "life.", "start": 3.447, "end": 3.708, "score": 0.949},
            ],
        },
    },
    {
        "audio": "/home/devank/Projects/VPipeline/renderer/public/audio/15.wav",
        "result": {
            "segments": [
                {
                    "start": 0.212,
                    "end": 7.654,
                    "text": " Despite ongoing searches, no definitive evidence of extraterrestrial civilizations has been found, leaving the Fermi paradox unresolved.",
                    "words": [
                        {
                            "word": "Despite",
                            "start": 0.212,
                            "end": 0.594,
                            "score": 0.849,
                        },
                        {
                            "word": "ongoing",
                            "start": 0.735,
                            "end": 1.097,
                            "score": 0.889,
                        },
                        {
                            "word": "searches,",
                            "start": 1.157,
                            "end": 1.6,
                            "score": 0.868,
                        },
                        {"word": "no", "start": 1.861, "end": 2.002, "score": 0.769},
                        {
                            "word": "definitive",
                            "start": 2.042,
                            "end": 2.525,
                            "score": 0.862,
                        },
                        {
                            "word": "evidence",
                            "start": 2.585,
                            "end": 2.907,
                            "score": 0.932,
                        },
                        {"word": "of", "start": 2.947, "end": 3.008, "score": 0.753},
                        {
                            "word": "extraterrestrial",
                            "start": 3.128,
                            "end": 3.893,
                            "score": 0.861,
                        },
                        {
                            "word": "civilizations",
                            "start": 3.953,
                            "end": 4.717,
                            "score": 0.909,
                        },
                        {"word": "has", "start": 4.757, "end": 4.898, "score": 0.889},
                        {"word": "been", "start": 4.918, "end": 5.079, "score": 0.99},
                        {
                            "word": "found,",
                            "start": 5.119,
                            "end": 5.481,
                            "score": 0.831,
                        },
                        {
                            "word": "leaving",
                            "start": 5.663,
                            "end": 5.944,
                            "score": 0.798,
                        },
                        {"word": "the", "start": 5.984, "end": 6.045, "score": 0.998},
                        {"word": "Fermi", "start": 6.085, "end": 6.387, "score": 0.663},
                        {"word": "paradox", "start": 6.427, "end": 6.93, "score": 0.87},
                        {
                            "word": "unresolved.",
                            "start": 7.03,
                            "end": 7.654,
                            "score": 0.956,
                        },
                    ],
                    "avg_logprob": -0.04044500827789307,
                }
            ],
            "word_segments": [
                {"word": "Despite", "start": 0.212, "end": 0.594, "score": 0.849},
                {"word": "ongoing", "start": 0.735, "end": 1.097, "score": 0.889},
                {"word": "searches,", "start": 1.157, "end": 1.6, "score": 0.868},
                {"word": "no", "start": 1.861, "end": 2.002, "score": 0.769},
                {"word": "definitive", "start": 2.042, "end": 2.525, "score": 0.862},
                {"word": "evidence", "start": 2.585, "end": 2.907, "score": 0.932},
                {"word": "of", "start": 2.947, "end": 3.008, "score": 0.753},
                {
                    "word": "extraterrestrial",
                    "start": 3.128,
                    "end": 3.893,
                    "score": 0.861,
                },
                {"word": "civilizations", "start": 3.953, "end": 4.717, "score": 0.909},
                {"word": "has", "start": 4.757, "end": 4.898, "score": 0.889},
                {"word": "been", "start": 4.918, "end": 5.079, "score": 0.99},
                {"word": "found,", "start": 5.119, "end": 5.481, "score": 0.831},
                {"word": "leaving", "start": 5.663, "end": 5.944, "score": 0.798},
                {"word": "the", "start": 5.984, "end": 6.045, "score": 0.998},
                {"word": "Fermi", "start": 6.085, "end": 6.387, "score": 0.663},
                {"word": "paradox", "start": 6.427, "end": 6.93, "score": 0.87},
                {"word": "unresolved.", "start": 7.03, "end": 7.654, "score": 0.956},
            ],
        },
    },
]


for audio in d:
    print(audio["audio"])
