from pydantic import BaseModel, Field

#Response State for the LLM (writer) @ /VPipeline/src/vcp/nodes/script/writer.py
#This is single state/format for the script with combined in list.
class ScriptSingle(BaseModel):
    #ID of each script. id=1, id=2 and so on.
    id: int = Field(description="Unique ID for each script.")
    #Actual script generated by the LLM
    script: str = Field(description="Single line script only. No full script but each Dailouge or line")

#Combined scripts as list of dictionaries.
#ScriptResponse(ScriptLine=[{id=1,script="content"},{id=2,script=""}])
class ScriptResponse(BaseModel):
    #Actual combination takes place below here.
    script: list[ScriptSingle]
