import operator
from typing import TypedDict, Annotated

from pydantic import Field

from vcp.schemas import (
    ResearchResponse,
    ScriptResponse,
    FormatResponse,
    AudioSegment,
    VisualResponse
)

#The class/state of the main graph @ /VPipeline/src/vcp/graph/graph.py: <29:5> builder = StateGraph(state) <-- state=GlobalState
class GlobalState(TypedDict):
    #Topic of the graph/user entered.
    topic: str = Field(description="Topic of whole operation.")

    #Category of the topic, decided by the LLM.
    #e.g: History, Space related etc
    category: str = Field(description="Category of topic")

    #Information gathered by the LLM (researcher) from the web about the topic
    information: ResearchResponse = Field(description="Information Researcher will add here that it got from web (Summarized Infoamtion, not raw metadata)")

    #Script generated by the LLM (writer) on the basis/facts gathered by the researcher. Something like this:
    #ScriptResponse(scriptLine=[{id=1,script="content"},{id=2,script="conent"}])
    script: ScriptResponse = Field(description="Script that Writer will write, will be added in list of dicts, each dict containing only one scentence of whole script.")

    #Annotated list of audio *paths*.
    #Annotated helps concatenate in lists into lists as str.
    #If not Annotated then the old list would replaced by the new list (path) generated by tts from langgraph.
    audio: Annotated[
    list[AudioSegment],
    operator.add
    ] = Field(description="Path of Audio Generated by TTS")

    #Default=0, this is batching purpose of the tts generation, currently using omnivoice which is VRAM heavy on comparatively lower end hardware (e.g: RTX 3050 6GB) if you want to generate
    #speech on GPU then you have to batch the porcess into value that is handable by the hardware and so to avoid *CUDA out of memory* error.
    #You can see the implementation of "tts_index" into "/VPipeline/src/vcp/service/tts/omni.py" @ line around 16-20
    tts_index: int = 0

    #Visual Response Generated by the LLM (Visualizer) will be usable in gathering assets/media from the internet. MORE DOCUMENTATION WHEN IT WILL BE IMPLEMENTED.
    visual: VisualResponse = Field(description="Segmented Script seperated by LLM for visual purposes")
